import moment from "moment";

export default interface ICourse {
    id: string,
    year: number,
    semester: string,
    coursePrefix: string,
    courseNumber: number,
    lastName: string,
    firstName: string,
    courseTitle: string,
    creditHours: number,
    creditVariation: string,
    courseCapacity: number,
    courseSection?: string,
    buildingCode?: string | null,
    roomCode?: string | null,
    onMonday?: string | null,
    onTuesday?: string | null,
    onWednesday?: string | null,
    onThursday?: string | null,
    onFriday?: string | null,
    startTime?: string | null,
    endTime?: string | null,
    preferredName?: string | null,

    overlap?: boolean | null,
    convertedStartDate?: moment.Moment | null,
    convertedEndDate?: moment.Moment | null,
}